# Generated by Django 3.1.4 on 2020-12-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'Memories'},
        ),
        migrations.AddField(
            model_name='memory',
            name='location',
            field=models.CharField(default='Paris', max_length=250),
            preserve_default=False,
        ),
    ]
